import {
  ESLINT_PLUGIN_CONFIG,
  JSDOC_ESLINT_PLUGIN_CONFIG,
  PRETTIER_ESLINT_PLUGIN_CONFIG,
  SIMPLE_IMPORT_SORT_ESLINT_PLUGIN_CONFIG,
  TYPESCRIPT_ESLINT_PLUGIN_CONFIG,
  UNUSED_IMPORTS_ESLINT_PLUGIN_CONFIG,
} from "#plugins";

/**
 * Common workspace eslint configuration.
 * @type {import('#types').ConfigWithExtends[]}
 */
export const BASE_WORKSPACE_ESLINT_CONFIG = [
  ...ESLINT_PLUGIN_CONFIG,
  ...TYPESCRIPT_ESLINT_PLUGIN_CONFIG,
  ...JSDOC_ESLINT_PLUGIN_CONFIG,
  ...SIMPLE_IMPORT_SORT_ESLINT_PLUGIN_CONFIG,
  ...UNUSED_IMPORTS_ESLINT_PLUGIN_CONFIG,
  ...PRETTIER_ESLINT_PLUGIN_CONFIG,
];
