import {
  ESLINT_CONFIG,
  JSDOC_ESLINT_CONFIG,
  PRETTIER_ESLINT_CONFIG,
  SIMPLE_IMPORT_SORT_ESLINT_CONFIG,
  UNUSED_IMPORTS_ESLINT_CONFIG,
} from "./src/index.mjs";

/**
 * @type {import('eslint').Linter.Config[]}
 */
export default [
  ...ESLINT_CONFIG,
  ...JSDOC_ESLINT_CONFIG,
  ...SIMPLE_IMPORT_SORT_ESLINT_CONFIG,
  ...UNUSED_IMPORTS_ESLINT_CONFIG,
  ...PRETTIER_ESLINT_CONFIG,
];
